# --prune for create environment from scratch
# conda env update --file environment.yml  --prune
# pyOpen manual install

name: e16-4yp-model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - numpy
  - requests
  - scikit-learn
  - tensorflow
  - tensorflow-gpu
  - jupyter
  
