# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: ""
remote_theme: cepdnaclk/e16-4yp-Enhancing Video Game Experience With Brain Computer Interface
description: "Developing a video game interface that uses the brain-computer interface (BCI) based on electroencephalography (EEG)."
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false

theme: jekyll-theme-leap-day